[?2004h(base) ]0;lahiru-menik@lahiru-menik-ASUS-EXPERTBOOK: ~/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever[01;32mlahiru-menik@lahiru-menik-ASUS-EXPERTBOOK[00m:[01;34m~/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever[00m$ rm -rf testbed/django
rm -rf testbed/django
[?2004l[?2004h(base) ]0;lahiru-menik@lahiru-menik-ASUS-EXPERTBOOK: ~/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever[01;32mlahiru-menik@lahiru-menik-ASUS-EXPERTBOOK[00m:[01;34m~/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever[00m$ cp -r django testbed
cp -r django testbed
[?2004l[?2004h(base) ]0;lahiru-menik@lahiru-menik-ASUS-EXPERTBOOK: ~/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever[01;32mlahiru-menik@lahiru-menik-ASUS-EXPERTBOOK[00m:[01;34m~/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever[00m$ docker run --mount type=bind,src=/home/lahiru-menik/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever/testbed/django,dst=/testbed -it django_5.0 bash
docker run --mount type=bind,src=/home/lahiru-menik/Documents/fyp/e19-4yp-Solve-Issues-In-Large-Code-Repositories/code/retriever/testbed/django,dst=/testbed -it django_5.0 bash
[?2004l[?2004h]0;sandbox@511cc1ce4998: /testbedsandbox@511cc1ce4998:/testbed$ source /opt/miniconda3/bin/activate py_3.11
source /opt/miniconda3/bin/activate py_3.11
[?2004l[?2004h(py_3.11) ]0;sandbox@511cc1ce4998: /testbedsandbox@511cc1ce4998:/testbed$ python -m pip install -e .
python -m pip install -e .
[?2004lDefaulting to user installation because normal site-packages is not writeable
Obtaining file:///testbed
  Installing build dependencies ... [?25l- \ | / - done
[?25h  Checking if build backend supports build_editable ... [?25ldone
[?25h  Getting requirements to build editable ... [?25l- error
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mGetting requirements to build editable[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m1[0m
  [31mâ•°â”€>[0m [31m[23 lines of output][0m
  [31m   [0m Traceback (most recent call last):
  [31m   [0m   File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
  [31m   [0m     main()
  [31m   [0m   File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
  [31m   [0m     json_out["return_val"] = hook(**hook_input["kwargs"])
  [31m   [0m                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 157, in get_requires_for_build_editable
  [31m   [0m     return hook(config_settings)
  [31m   [0m            ^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-arzlwk20/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 473, in get_requires_for_build_editable
  [31m   [0m     return self.get_requires_for_build_wheel(config_settings)
  [31m   [0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-arzlwk20/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
  [31m   [0m     return self._get_build_requires(config_settings, requirements=[])
  [31m   [0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-arzlwk20/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
  [31m   [0m     self.run_setup()
  [31m   [0m   File "/tmp/pip-build-env-arzlwk20/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 317, in run_setup
  [31m   [0m     exec(code, locals())
  [31m   [0m   File "<string>", line 54
  [31m   [0m     % {"existing_path":
  [31m   [0m       ^
  [31m   [0m SyntaxError: '{' was never closed
  [31m   [0m [31m[end of output][0m
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
[1;31merror[0m: [1msubprocess-exited-with-error[0m

[31mÃ—[0m [32mGetting requirements to build editable[0m did not run successfully.
[31mâ”‚[0m exit code: [1;36m1[0m
[31mâ•°â”€>[0m See above for output.

[1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
[?25h[?2004h(py_3.11) ]0;sandbox@511cc1ce4998: /testbedsandbox@511cc1ce4998:/testbed$ python -m pip install -e .
python -m pip install -e .
[?2004lDefaulting to user installation because normal site-packages is not writeable
Obtaining file:///testbed
  Installing build dependencies ... [?25l- \ done
[?25h  Checking if build backend supports build_editable ... [?25ldone
[?25h  Getting requirements to build editable ... [?25l- error
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mGetting requirements to build editable[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m1[0m
  [31mâ•°â”€>[0m [31m[23 lines of output][0m
  [31m   [0m Traceback (most recent call last):
  [31m   [0m   File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
  [31m   [0m     main()
  [31m   [0m   File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
  [31m   [0m     json_out["return_val"] = hook(**hook_input["kwargs"])
  [31m   [0m                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 157, in get_requires_for_build_editable
  [31m   [0m     return hook(config_settings)
  [31m   [0m            ^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-kws7okdc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 473, in get_requires_for_build_editable
  [31m   [0m     return self.get_requires_for_build_wheel(config_settings)
  [31m   [0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-kws7okdc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
  [31m   [0m     return self._get_build_requires(config_settings, requirements=[])
  [31m   [0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [31m   [0m   File "/tmp/pip-build-env-kws7okdc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
  [31m   [0m     self.run_setup()
  [31m   [0m   File "/tmp/pip-build-env-kws7okdc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 317, in run_setup
  [31m   [0m     exec(code, locals())
  [31m   [0m   File "<string>", line 54
  [31m   [0m     % {"existing_path":
  [31m   [0m       ^
  [31m   [0m SyntaxError: '{' was never closed
  [31m   [0m [31m[end of output][0m
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
[1;31merror[0m: [1msubprocess-exited-with-error[0m

[31mÃ—[0m [32mGetting requirements to build editable[0m did not run successfully.
[31mâ”‚[0m exit code: [1;36m1[0m
[31mâ•°â”€>[0m See above for output.

[1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
[?25h[?2004h(py_3.11) ]0;sandbox@511cc1ce4998: /testbedsandbox@511cc1ce4998:/testbed$ pip install -r tests/requirements/py3.txt
pip install -r tests/requirements/py3.txxt
[?2004lDefaulting to user installation because normal site-packages is not writeable
[31mERROR: Exception:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/markers.py", line 280, in __init__
    self._markers = _normalize_extra_values(_parse_marker(marker))
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 253, in parse_marker
    return _parse_full_marker(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 257, in _parse_full_marker
    retval = _parse_marker(tokenizer)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 266, in _parse_marker
    expression = [_parse_marker_atom(tokenizer)]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 291, in _parse_marker_atom
    marker = _parse_marker_item(tokenizer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 301, in _parse_marker_item
    marker_var_left = _parse_marker_var(tokenizer)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 319, in _parse_marker_var
    tokenizer.raise_syntax_error(
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/_tokenizer.py", line 168, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: Expected a marker variable or quoted string
    sys.pla
    ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 68, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 351, in run
    reqs = self.get_requirements(args, options, finder, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 271, in get_requirements
    req_to_add = install_req_from_parsed_requirement(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/req/constructors.py", line 480, in install_req_from_parsed_requirement
    req = install_req_from_line(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/req/constructors.py", line 405, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_internal/req/constructors.py", line 318, in parse_req_from_line
    markers = Marker(markers_as_string)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py_3.11/lib/python3.11/site-packages/pip/_vendor/packaging/markers.py", line 298, in __init__
    raise InvalidMarker(str(e)) from e
pip._vendor.packaging.markers.InvalidMarker: Expected a marker variable or quoted string
    sys.pla
    ^[0m[31m
[0m[?2004h(py_3.11) ]0;sandbox@511cc1ce4998: /testbedsandbox@511cc1ce4998:/testbed$ [K./tests/runtests.py --verbosity 2 --settings=test_sqlite --parallel 1 migrations.test_writer.WriterTests.test_serialize_nested_class_method
./tests/runtests.py --verbosity 2 --setttings=test_sqlite --parallel 1 migrations.test_writer.WriterTests.test_serialize__nested_class_method
[?2004l  File "/testbed/./tests/runtests.py", line 735
    if options.se
                 ^
SyntaxError: expected ':'
[?2004h(py_3.11) ]0;sandbox@511cc1ce4998: /testbedsandbox@511cc1ce4998:/testbed$ [Kexit
